//Lexical grammar (tokens)
%lex

%%

\s+ /* skip whitespace */

\<(.*?)\> return 'TUPLE'

\"[^"]*\" return 'STRING'

[+-]?[0-9]+\/[0-9]+ return 'RAT'

[+-]?\d+\b(?![\.\/]) return 'INT'

[+-]?([0-9]*[.])[0-9]+ return 'NUM'

[\w\-+*=/&\|\^!<>\%]+ return 'SYMBOL' 

\{((.+?):(.+?))*\}|/\{([^:]|\,\s*)*\} return 'TABLE'

/lex

%%

Exp
    : Atom
    | List
    ;
    
Atom 
    : RAT
    | INT {
        const modules = require('../modules.js');
        const BigInteger = require('big-integer')
        var flipflag = Math.sign(parseFloat($1))
        var a = $1.replace(/[/-]/g, '')
        $$ = new modules.int._Int(modules.int._Int.bigToBT(BigInteger(a))).mul(flipflag)
    }
    | NUM {
        const modules = require('../modules.js');
        $$ = new modules.num._Num(parseFloat($1));
    }
    | STRING {
        const modules = require('../modules.js');
        $$ = new modules.string._String(modules.string.unicodeEscape($1.slice(1,-1)))
    }
    | TABLE
    | TUPLE
    | SYMBOL 
    ;

List
    : '(' ListEntries ')'       { $$ = $2 }
    ;




ListEntries
    : ListEntries Exp   { $1.push($2); $$ = $1}
    | /* empty */       { $$ = [] }
    ;
